### ISSUE TITLE
Error on save and send in Outbound Email (SparkPost)

### ISSUE THREAD

**Issue by kcristiano** [cividesk/com.cividesk.email.sparkpost#1]
CiviCRM 4.7.3, WordPress 4.4.2

Setup SparkPost API key.   Added via Outbound Email (SparkPost).  Saved settings and received these errors:
SparkPost errors
Could not install webhook (Sparkpost error(s): POST to webhook target URL failed with response code 302).
SparkPost errors
Could not install/refresh webhook.

Test mail came through, however scheduled mailings do not.

**Comment by nganivet** [comment]
You must have an HTTP redirect on your CiviCRM root URL (maybe http to https?). I am using the CRM_Utils_System::url() function to create the postback URL, and this URL must return a 200 status code for SpakPost. Yours is now returning a redirect.

**Comment by kcristiano** [comment]
We do have a redirect http to https in the vhost.  But I don't think that is it.
Looking here:  https://github.com/cividesk/com.cividesk.email.sparkpost/blob/master/CRM/Admin/Form/Setting/Sparkpost.php#L135  You set the call back.

On WP this results in 
https://example.org/civicrm/?page=CiviCRM&amp;q=civicrm/sparkpost/callback

That URL does not exist and redirects (the 302) to the default CiviCRM basepage.    Have you tested on a WP install yet?   If you have can you confirm the callback url you get?

**Comment by nganivet** [comment]
Kevin - never tried on WordPress, only on Drupal or Standalone which both have pretty URLs. This might be due to the &amp; instead of just &

Can you try replacing line 135 with the following:
'target' => CRM_Utils_System::url('civicrm/sparkpost/callback', NULL, TRUE, NULL, FALSE);
(note the 2 extra parameters)

If this still does not work you mighthave to play with the last 2 paramaters in the call, but I would not know how to set them properly for a callback URL:
   * @param bool $frontend
   *   This link should be to the CMS front end (applies to WP & Joomla).
   * @param bool $forceBackend
   *   This link should be to the CMS back end (applies to WP & Joomla).
