### ISSUE TITLE
Not reflecting all bounces

### ISSUE THREAD

**Issue by davyrhys** [cividesk/com.cividesk.email.sparkpost#18]
Your extension has been a great addition to my site. Thankyou! 

However I can't reconcile bounce reports on Sparkpost with CiviMail. It appears that certain bounces aren't reflecting correctly. On the mailing below Sparkpost reflects 27 bounces (20 blocks, 3 hard, 2 admin, 2 soft) whereas CiviMail only reflects 2 bounces. 

Can you help? I'm using CiviCRM 4.7.4 on Drupal 6, with PHP5.4

![screen shot 2016-04-12 at 12 09 14](https://cloud.githubusercontent.com/assets/1043028/14471493/32e681f6-00ef-11e6-83d6-c6c41e1ea8f2.png)

![screen shot 2016-04-12 at 10 08 20](https://cloud.githubusercontent.com/assets/1043028/14471517/49876c36-00ef-11e6-9697-b2749738e515.png)

**Comment by nganivet** [comment]
Can you please make a screenshot (or better, export to csv) of the 
bottom part of the Reports / Bounces screen? I would need to see the 
reason, category and classification columns. You can obscure/delete the 
domain column for privacy reasons. Thanks.

------ Original Message ------

**Comment by davyrhys** [comment]
Thanks for looking into this. Below is the report as requested.
[Sparkpost bounce report.xlsx](https://github.com/cividesk/com.cividesk.email.sparkpost/files/216021/Sparkpost.bounce.report.xlsx)

**Comment by nganivet** [comment]
All these cases are managed in the extension, so it is strange that they 
do not appear in CiviMail. A possible explanation is that the bounces 
are from transactional emails rather than your CiviMail mailing. If this 
is the case, please remember that CiviCRM does not process such bounces 
- so for example if an event confirmation email bounces it is ignored by 
CiviCRM - but will appear as a bounce in Sparkpost.

Could this be the case or are you positive that all these bounces 
occurred as a result of your CiviMail mailing?

------ Original Message ------

**Comment by PalanteJon** [comment]
@nganivet I just installed the extension and did a test mailing (using CiviMail, not transactional mail).  I sent the mail to two addresses - one valid, one invalid.  The bounce isn't showing up in Civi's mailing report for me.  Since it sounds like it's the same issue, I'm going to attach the CSV showing the SparkPost bounce that's not showing up in Civi.  
[export_data_04132016_162221.txt](https://github.com/cividesk/com.cividesk.email.sparkpost/files/217895/export_data_04132016_162221.txt)

**Comment by nganivet** [comment]
Thanks Jon, I will do some more testing on my side and get this 
corrected.

------ Original Message ------

**Comment by PalanteJon** [comment]
Thanks Nicolas.  Feel free to send as many messages as you want to that
email address that didn't register a bounce.  The address is
bounce@misandry.co, it's my coworker's domain and we routinely use it
for bounce testing.
