### ISSUE TITLE
Mail sent from Forward Mailing links bounce

### ISSUE THREAD

**Issue by GinkgoFJG** [cividesk/com.cividesk.email.sparkpost#21]
Hi, N,

Not sure if this is an extension issue or a core issue. I think the core form in question is quite old and not very well-maintained...

In any case, you may recall that putting the {action.forward} token in an email generates a link through which users may forward messages to their friends. From what I can see in sparkpost_log, the generated email puts the subscriber's email in the FROM header and the domain address in the REPLY-TO header.

As you know, SparkPost will not allow sending from off-domain addresses. To work with SparkPost, the message must come from an organization address. It's unclear to me whether the problem is that the core form is designed to send from the constituent address or that the extension is mishandling params. Any insight?

**Comment by nganivet** [comment]
The extension is just passing through the parameters that are given to it by CiviCRM, so we certainly do not replace the From: or any other parameter (cf. CRM/Mail/Sparkpost.php file).

I think the issue is with the CRM: we should NOT impersonate the subscriber when sending the email by using his address as From: in the email. That certainly will not work with SPF/DKIM checking that most domains now implement, and all big providers (Yahoo, GMail, etc) that detect such internationalization (using the message_id that they insert in the headers) will block any such emails immediately and lower you reputation.

So ... do you feel inclined to do a PR in core to fix this? We should instead have the domain's default From: email address as From: in the email, and maybe add a small paragraph in the email to say "John Smith (john.smith458@gmail.com) has forwarded this message to you."

**Comment by GinkgoFJG** [comment]
I agree that impersonating the constitute is a bad idea. I'll open an issue and assign it to myself, but I have another more burning issue to deal with first which will show up in your queue shortly :-/

**Comment by GinkgoFJG** [comment]
For reference, the core issue is [CRM-18458](https://issues.civicrm.org/jira/browse/CRM-18458).

**Comment by nganivet** [comment]
Thanks. Documentation updated.

------ Original Message ------
