### ISSUE TITLE
info message "Name should be provided."

### ISSUE THREAD

**Issue by cdhassell** [cividesk/com.cividesk.email.sparkpost#28]
My logs are filling up with messages like:

> May 14 00:00:05  [info] Deprecated: Group='SparkPost Extension Settings'. Name should be provided.

I haven't been able to determine what name this refers to.  Can you point me in the right direction?

**Comment by nganivet** [comment]
This is due to changes in the 4.7 API for function CRM_Core_BAO_Setting::getItem(), thanks for pointing this out. The latest commit solves this issue. Please update (using git pull) and there will be no more warnings in your logs.

**Show your support!**

Development of this extension was fully self-funded by Cividesk and equated to about 30 hours of work.

You can show your support and appreciation for our work by making a donation at https://www.cividesk.com/pay and indicating 'SparkPost support' as the invoice id.

Suggested donation amounts are $40 for end-users, and $40 per client using this extension for service providers. With these suggested amounts, we would need 90 donations just to recoup our development costs.

These donations will fund maintenance and updates for this extension, as well as production of other extensions in the future.

Thanks!
