### ISSUE TITLE
Bounces are not counted in CiviCRM

### ISSUE THREAD

**Issue by ritatorok** [cividesk/com.cividesk.email.sparkpost#31]
Hello,

We updated the Sparkpost extension to version 1.1 and tested if the bounces are correct in CiviCRM. Unfortunately there are no bounces counted in Civicrm, but there are lots of bounces in Sparkpost. We have tried with sending only for 2 email addresses, one of them is a wrong email address, and tried sending for 12 addresses, many of them should have been bounced, but none of them are in Civicrm. We have a scheduled job to fetch bounces, we ran it many times. These emails were sent last week on Friday, and waited till Monday to make sure they get bounced in Sparkpost, but they are still not counted in Civi. Do you have any idea what might be wrong?

Thank you!

Best,
Rita Torok

<img width="1042" alt="screen shot 2016-07-25 at 09 55 37" src="https://cloud.githubusercontent.com/assets/20599002/17095964/0b335484-524f-11e6-9f94-5018af0a57ae.png">
<img width="951" alt="screen shot 2016-07-25 at 09 55 52" src="https://cloud.githubusercontent.com/assets/20599002/17095965/0b34e934-524f-11e6-9555-fc8f5fd9998a.png">

**Comment by nc3man** [comment]
I have exactly the same issue. My screenshot looks just like the one in the post above, so no need to repeat. BTW, evertyhing else works GREAT. Test email worked and test jobs had the correct number of opens and click-throughs. I checked the corresponding Scheduled Jobs log for fetching the bounces and got

> Entity: job Action: fetch_bounces
> Summary
> Finished execution of Fetch Bounces with result: Failure, Error message: A fatal error was triggered: Could not connect to MailStore for postmaster@
> Error message:
> An error occured while sending or receiving mail. Failed to conn (...)
> Details
> Parameters raw (From Cli.php): 
> a:2:{s:7:"version";i:3;s:31:"ssdbikecoalition.sdcbcdream.org";N;}
> Parameters parsed (and passed to API method): 
> a:2:{s:7:"version";i:3;s:31:"ssdbikecoalition.sdcbcdream.org";N;}
> Full message: 
> Finished execution of Fetch Bounces with result: Failure, Error message: A fatal error was triggered: Could not connect to MailStore for postmaster@
> Error message: 
> An error occured while sending or receiving mail. Failed to connect to the server: :110.
> 

I hope that may help diagnose. The From and Reply-To fields for these emails are postmaster@sdbikecoalition.sdcbcdream.org and the domain name seems to be truncated from the error messages

**Comment by nc3man** [comment]
I should also add that my cron job on my host (Dreamhost) runs a bash script with these lines (not exposing the username and password):

> CIVI_ROOT="/home/karrud1/sdbikecoalition/wp-content/plugins/civicrm/civicrm"
> PARAMS="-j -ssdbikecoalition.sdcbcdream.org -u {usr} -p {pwd} -e Job -a fetch_bounces"
> php $CIVI_ROOT/bin/cli.php $PARAMS
> 

Perhaps I need to pass in different parameters. The (usr,pwd) combo is my Wordpress Admin account, from where I then administer the Wordpress CiviCRM plugin (more than a plugin, really ;)).  The same command with fetch_bounces replaced by process_mailing correctly process the CiviCRM mail queue through Sparkpost.

**Comment by nc3man** [comment]
I have good news and bad news. After waiting 3 days, the bounces at SparkPost were finally incremented and this DID show up in the CiviCRM mail reports. However, I still get the error message in my Scheduled Jobs fetch_bounces log.

> Finished execution of Fetch Bounces with result: Failure, Error message: A fatal error was triggered: Could not connect to MailStore for postmaster@
> Error message:
> An error occured while sending or receiving mail. Failed to conn (...)

I suppose this is a non-issue or some simple cleanup since the bounce reporting appears to be working. I would like the logs to indicate successful completion. Is anyone at CiviDesk monitoring this thread, or should I just open a separate issue? [which I will if no reponse continues]

**Comment by nganivet** [comment]
nc3man - the error you are experiencing has nothing to do with Sparkpost. Closing the thread.

**Comment by nganivet** [comment]
Bringing clarity to the above comment: with this extension, the bounces are NOT registered with the Fetch Bounces job, but with a Sparkpost callback. If you ran through the setup screen this callback should have been installed, but you can check in your Sparkpost setup that it is setup correctly. Because of the callback, bounces are registered in CiviCRM in real-time, so there should not be any delays.
