### ISSUE TITLE
Sync CiviCRM on-hold list with sparkpost suppression list

### ISSUE THREAD

**Issue by gppetermcandrew** [cividesk/com.cividesk.email.sparkpost#46]
Feature request:  an email should be removed from the sparkpost suppression list if the on-hold flag is removed from Civi otherwise an email has to be un-holded in two places.

* there's another request against a different extension here: https://github.com/proexchange/com.pesc.sparkpost/issues/1

**Comment by nganivet** [comment]
You usually do not want to remove a 'On Hold' flag since this indicates an invalid email address, or an email address that has flagged/reported your emails as spam. Continuing to send to such email addresses is the fastest way for your domain, or sending IP, to be blacklisted.

What is your use case for wanting this feature?

**Comment by TheGreenParty** [comment]
Legitimate use is that a subscriber may have marked an email as spam in their client and gone on to suppression list.  Then months later calls you up and asks to receive emails again.

There are many such legitimate cases for removing people from suppression lists so that they are not immutable, hence spark post allow you to do this via the UI and the API.  The fact is that I can uncheck someone in Civi and can go to spark post and remove them manually from the suppression list.   This request is just to integrate the two.

**Comment by nganivet** [comment]
OK, now I understand. I have been asked way to many time by my customers to 're-enable everyone that has the On Hold flag in CiviCRM'. As long as this is on a case-by-case basis it is fine.

Would you have any funding for such a development? We're probably looking at $700-$900 USD including developments, tests and packaging a new release of the extension.

**Comment by TheGreenParty** [comment]
Hi,  I could certainly help fund it. I might have to split that over 2 months in terms of my budget.  Do you have any issues with that, i.e. sending 2 invoices one in April and one in May?


Would the solution you produce also work if the 'on hold' was removed via the CiviAPI and not just via the UI?  It's not a deal breaker but we have a custom interface to Civi records that some people use which modifies contact records via the API.  If someone used that to update the on-hold flag I would also want the address removed from the Sparkpost suppression list.

________________________________

**Comment by nganivet** [comment]
Let's continue this conversation privately. Can you email me at nicolas at cividesk dot com? Thanks.

**Comment by nganivet** [comment]
@TheGreenParty This feature has been implemented and will be released shortly. Can you please respond to my emails and process the invoice I sent you? Thanks.

**Comment by nganivet** [comment]
@TheGreenParty Closing as fixed in the latest release. Very classy of you to agree to fund this development, and then not answer any of my emails afterwards when asking you to make good on your commitment ...
