### ISSUE TITLE
Make callback URL configurable

### ISSUE THREAD

**Issue by michaelmcandrew** [cividesk/com.cividesk.email.sparkpost#51]
Problem:
A CiviCRM instance is running on a private network with a Proxy that is set up (using [CiviProxy](https://github.com/systopia/CiviProxy)) to handle necessary communication with the outside world. Callbacks that are automatically configured by the extension will not reach the CiviCRM instance.

Proposed solution:
Add an option to the sparkpost admin settings form that allows the callback URL to be specified so that when the form is submitted and the setting is create/refreshed it is set to an appropriate URL on the proxy.

Happy to submit a PR along these lines if this sounds like an acceptable approach to you.

**Comment by nganivet** [comment]
I think you can just change the callback URL in the SparkPost console (Account > WebHooks menu) and it will not get modified afterwards even if you run gthe setup screen again (to be verified). If this does not work then an additional setting seems like a nice way to solve the issue. Just make sure that the system interprets empty URL as the default one so the upgrade is smooth. Also add a helptext on the setting saying it's optional. Thanks.

**Comment by michaelmcandrew** [comment]
Hey @nganivet. Thanks for your response.

My assumption, based on [this comment](https://github.com/cividesk/com.cividesk.email.sparkpost/blob/db4003ae3d32d33a850c096a669c996d4a59e768/CRM/Admin/Form/Setting/Sparkpost.php#L165) was that it would get overwritten. I will confirm what happens.

If all the same with you, I think it makes sense to implement the option because 1) it'll catch any edge cases and 2) otherwise the operator has to remember to log back into sparkpost on every change.

I will note what you have said above about defaults, help texts and upgrades, etc. when doing the implementation. The PR won't be imminent but should be in by the end of this year at the latest (the proxy is not set up, we are planning ahead, etc.).

**Comment by michaelmcandrew** [comment]
Hello again,

So the webform will not get overwritten if you just save the form, but it will get overridden if you save and send test email.

PR coming up...

**Comment by michaelmcandrew** [comment]
@nganivet. Do you have a release process in place for this module? Just wondering when we can expect this functionality in a a released version.

**Comment by nganivet** [comment]
No release process - I simply did not raise enough funds to maintain this extension. Development has been fully self-funded and it took a LOT of time. I cannot afford to put more time in for maintenance now.

The home page is asking for a $40 donation per client/install, which I thought was very reasonable, but I only got less than _one_ handful of donations out of 575+installs. Bugs me even more as I have contributed very significantly to funding other partners for extensions.

I had a good roadmap for this extension with improvements and new features planned. Will not be executed, but the extension will keep on being updated to work with the latest CiviCRM releases since I am using it internally with all my customers.
