### ISSUE TITLE
Use new crm-region instead of overriding smtp settings page

### ISSUE THREAD

**Issue by mattwire** [cividesk/com.cividesk.email.sparkpost#56]
From CiviCRM 4.7.31 there is a new setting "Allow Mail to be sent from logged in contact's email address" on the Outbound mail settings.  A new crm-region has been created to allow overriding the default mailer settings:
https://github.com/civicrm/civicrm-core/blob/master/templates/CRM/Admin/Form/Setting/Smtp.tpl#L36

**Comment by nganivet** [comment]
@mattwire Thanks for your comment. If I understand there are 2 items:

1. There is a new setting that my extension does not implement yet (since was not available before),
1. There is a new way of overriding email settings (rather than hijacking the settings menu as currently)

For 2. I cannot really change what I am doing now since I need to have both my own settings page, as well as the regular settings page for the backup mailer (in case you are trying to send with a from: address not in the domains you have verified with SP).

For 1. I am in a time crunch now, and since less than a handful of people have contributed the minuscule amount of money I am asking for this extension, do not have a lot of motivation to spend more time on it. Patch welcome!

**Comment by mattwire** [comment]
@nganivet For 1. you don't need to do anything, it's independent of any extension.

For 2. well it's a UI only thing, so it's probably fine for now but might be nice to tidy up somehow if we get the opportunity.

**Comment by nganivet** [comment]
@mattwire Thanks, closing issue then.
